[platformio]
default_envs = crsf_rx_only

[env]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-rp2040
framework = arduino
lib_deps = adafruit/Adafruit TinyUSB Library@^3.7.3
build_flags = -DUSE_TINYUSB

[env:mavlink_rx_only]
monitor_speed = 460800
build_flags =
  ${env.build_flags}
  -DUART_RX_ONLY_MODE
  -DBRIDGE_UART_BAUD=460800

[env:crsf_rx_only]
monitor_speed = 420000
build_flags =
  ${env.build_flags}
  -DUART_RX_ONLY_MODE
  -DBRIDGE_UART_BAUD=420000

[env:crsf_inverted_rx_only]
monitor_speed = 420000
build_flags =
  ${env.build_flags}
  -DUART_RX_ONLY_MODE
  -DUART_INVERT_RX
  -DBRIDGE_UART_BAUD=420000

[env:uart_config_bridge]
monitor_speed = 460800
build_flags =
  ${env.build_flags}
  -DUART_BRIDGE_MODE
  -DBRIDGE_UART_BAUD=460800

[env:elrs_config_bridge]
monitor_speed = 420000
build_flags =
  ${env.build_flags}
  -DUART_BRIDGE_MODE
  -DUART_FOLLOW_USB_BAUD
  -DBRIDGE_UART_BAUD=420000

[env:uart_diagnostic]
monitor_speed = 115200
build_flags =
  ${env.build_flags}
  -DUART_DIAGNOSTIC_MODE
  -DBRIDGE_UART_BAUD=420000

[env:crsf_hid]
monitor_speed = 420000
build_flags =
  ${env.build_flags}
  -DCRSF_HID_MODE
